SELECT BOOK.AUTHOR_ID, AUTHOR.AUTHOR_NAME, BOOK.CATEGORY, SUM(BOOK_SALES.SALES * BOOK.PRICE) AS TOTAL_PRICE
FROM BOOK INNER JOIN BOOK_SALES
ON BOOK.BOOK_ID = BOOK_SALES.BOOK_ID
INNER JOIN AUTHOR
ON AUTHOR.AUTHOR_ID = BOOK.AUTHOR_ID
WHERE TO_CHAR(BOOK_SALES.SALES_DATE, 'YYYY-MM') = '2022-01'
GROUP BY BOOK.AUTHOR_ID, AUTHOR.AUTHOR_NAME, BOOK.CATEGORY
ORDER BY BOOK.AUTHOR_ID ASC, BOOK.CATEGORY DESC