WITH REGISTER_INFO AS (
    SELECT
        WRITER_ID
    FROM
        USED_GOODS_BOARD
    GROUP BY
        WRITER_ID
    HAVING
        COUNT(WRITER_ID) >= 3
)

SELECT
    UGU.USER_ID,
    UGU.NICKNAME,
    UGU.CITY || ' ' || UGU.STREET_ADDRESS1 || ' ' || NVL(UGU.STREET_ADDRESS2, '') AS "전체주소",
    SUBSTR(UGU.TLNO, 1, 3) || '-' || SUBSTR(UGU.TLNO, 4, 4) || '-' || SUBSTR(UGU.TLNO, 8) AS "전화번호"
FROM
    USED_GOODS_USER UGU
JOIN
    REGISTER_INFO RI ON UGU.USER_ID = RI.WRITER_ID
ORDER BY
    UGU.USER_ID DESC;