SELECT  A.PRODUCT_ID, B.PRODUCT_NAME, SUM(A.AMOUNT) * B.PRICE AS TOTAL_SALES
  FROM FOOD_ORDER A, FOOD_PRODUCT B
 WHERE A.PRODUCT_ID = B.PRODUCT_ID
   AND A.PRODUCE_DATE BETWEEN TO_DATE('2022-05-01','YYYY-MM-DD') AND TO_DATE('2022-05-31','YYYY-MM-DD')
GROUP BY A.PRODUCT_ID, B.PRODUCT_NAME, B.PRICE
ORDER BY TOTAL_SALES DESC, PRODUCT_ID ASC;