SELECT F.USER_ID, F.NICKNAME, SUM(B.PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD B, USED_GOODS_USER F
WHERE (B.WRITER_ID = F.USER_ID) 
AND
B.STATUS = 'DONE'
GROUP BY F.USER_ID, F.NICKNAME
HAVING SUM(B.PRICE) >= 700000
ORDER BY TOTAL_SALES;
